services:
  wordpress:
    build: .
    container_name: site
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_DATABASE', '1');
    volumes:
      - wordpress_data:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/custom_theme
    depends_on:
      - db
      - redis

  db:
    image: mariadb:11
    container_name: dev_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    tty: true
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "--appendonly",
      "yes"
    ]
    volumes:
      - redis_data:/data
      
volumes:
  wordpress_data:
  db_data:
  redis_data: